/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ywOELn72abi
 */

import { ConnectButton } from "./web3/connect-button";

export function Header() {
  return (
    <header className="flex justify-between items-center py-4 px-6 bg-gray-900">
      <h1 className="text-lg font-semibold text-white">Credibility Guard</h1>
      <ConnectButton />
    </header>
  )
}
